version: '3.8'

networks:
  web:
    external: true

services:
  nginx:
    image: dariuszbloch/moja-aplikacja-nginx:latest
    networks:
      - web
    container_name: ${IMAGE_NAME}-NGINX
    env_file:
      - .env
    ports:
      - "8083:80"
    depends_on:
      - php
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.darek.rule=Host(`darek.vps1.m89.pl`)"
        - "traefik.http.routers.darek.entrypoints=web"
        - "traefik.http.services.darek.loadbalancer.server.port=80"

  php:
    image: dariuszbloch/moja-aplikacja-php:latest
    container_name: ${IMAGE_NAME}-PHP
    env_file:
      - .env
    networks:
      - web

  db:
    image: dariuszbloch/moja-aplikacja-sql:latest
    container_name: ${IMAGE_NAME}-MYSQL
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - web
