services:
  nginx:
    image: dariuszbloch/moja-aplikacja-nginx:latest
    container_name: ${IMAGE_NAME}-NGINX
    env_file:
      - .env
    ports:
      - "8081:80"
    depends_on:
      - php
    networks:
      - backend

  php:
    image: dariuszbloch/moja-aplikacja-php:latest
    container_name: ${IMAGE_NAME}-PHP
    env_file:
      - .env
    networks:
      - backend

  db:
    image: dariuszbloch/moja-aplikacja-sql:latest
    container_name: ${IMAGE_NAME}-MYSQL
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

networks:
  backend:
    name: app-network
    driver: bridge
