version: '3.8'

networks:
  web:
    external: true

services:
  nginx-secret:
    image: dariuszbloch/moja-aplikacja-nginx2:latest
    secrets:
      - secret_demo
    command: ["sh", "-c", "while true; do cat /run/secrets/secret_demo; sleep 10; done"]
    networks:
      - web
    container_name: ${IMAGE_NAME}-NGINX
    env_file:
      - .env
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - php
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.darek.rule=Host(`darek.vps1.m89.pl`)"
        - "traefik.http.routers.darek.entrypoints=web"
        - "traefik.http.services.darek.loadbalancer.server.port=80"
secrets:
  secret_demo:
   file: ./nginx-secret/secrets.txt

  php:
    image: dariuszbloch/moja-aplikacja-php2:latest
    container_name: ${IMAGE_NAME}-PHP
    env_file:
      - .env
    networks:
      - web

  db:
    image: dariuszbloch/moja-aplikacja-sql2:latest
    container_name: ${IMAGE_NAME}-MYSQL
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - web
