version: '3.8'

networks:
  web:
    external: true

services:
  nginx-configd:
    image: nginx:alpine
#    configs:
#      - source: custom_nginx_conf
#        target: /etc/nginx/nginx.conf
    networks:
      - web
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.dariusz.rule=Host(`dariusz.vps1.m89.pl`)"
        - "traefik.http.routers.dariusz.entrypoints=web"
        - "traefik.http.services.dariusz.loadbalancer.server.port=80"

configs:
  custom_nginx_conf:
    file: ./nginx-conf/nginxd.conf
